name: Build and Release Desktop App

on:
  workflow_dispatch:
    inputs:
      gradle_task:
        description: 'The Gradle task to run.'
        required: true
        default: ':desktopApp:packageReleaseDmg'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build and package desktop app
        run: |
          ./gradlew --stacktrace ${{ inputs.gradle_task }}

      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: desktop-build-logs
          path: .desktopApp/build/compose/logs/proguardReleaseJars/

      - name: Upload DMG file
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: desktop-app-release.dmg
          path: ./desktopApp/build/distributions/desktopApp-release.dmg